module.exports = {
  content: [
    './pages/**/*.{html,js}', 
    './components/**/*.{html,js}',
    '•/pages/**/*.{vue, js, ts, jsx, tsx)' ,
    '/components/**/*. (vue, js, ts, jsx, tsx}' ,
    './app/**/*.{vue, js, ts, jsx, tsx}',
    './node_modules/@shadcn/**/*.{vue,js,ts,jsx,tsx}'
  ],
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
  daisyui: {
    themes: [
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
    ],
  },
}